export const LOGIN = '[AUTH] LOGIN';
export const LOGIN_SUCCESS = '[AUTH] LOGIN SUCCESS';
export const LOGIN_FAILURE = '[AUTH] LOGIN FAILURE';
export const INIT_USER_DATA = '[AUTH] INIT USER DATA';
export const INIT_USER_DATA_SUCCESS = '[AUTH] INIT USER DATA SUCCESS';