export const LOGIN = '[AUTH] LOGIN';
export const LOGIN_SUCCESS = '[AUTH] LOGIN SUCCESS';
export const LOGIN_FAILURE = '[AUTH] LOGIN FAILURE';
export const INIT_USER_DATA = '[AUTH] INIT USER DATA';
export const INIT_USER_DATA_SUCCESS = '[AUTH] INIT USER DATA SUCCESS';
export const CLEAR_RESPONSE_ERROR = '[AUTH] CLEAR RESPONSE ERROR';
export const FETCH_CONFIGURATION = '[AUTH] FETCH CONFIGURATION';
export const CONFIGURATION_FETCHED = '[AUTH] CONFIGURATION FETCHED';